# Generated by Django 3.0.6 on 2020-06-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_publist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulist',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
